export const CHATS_DATA = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  'Nunc egestas purus ut lectus suscipit, vitae condimentum arcu aliquet.',
  'Vestibulum fermentum libero at purus sagittis dapibus.',
  'Morbi non dui varius, porttitor justo vitae, imperdiet augue.',
  'Nunc feugiat massa et ante malesuada, eu venenatis ipsum euismod.',
  'Curabitur vel lacus non mauris gravida posuere.',
  'Curabitur non turpis vitae neque tristique luctus.',
  'Nunc auctor purus id sem placerat congue.',
  'Curabitur varius tortor et magna volutpat pharetra.',
  'In non ante consequat, aliquam odio eget, elementum diam.',
  'Phasellus tincidunt ante a feugiat luctus.',
  'Sed ac lectus iaculis, pulvinar arcu ac, vehicula enim.',
  'In semper ante quis mollis sollicitudin.',
  'Proin cursus enim nec scelerisque rhoncus.',
  'Quisque varius ex ut turpis tristique, tincidunt imperdiet augue condimentum.',
  'Cras vitae sem blandit augue feugiat laoreet vitae et tortor.',
  'Donec tincidunt ligula id porta tempor.',
  'Cras sed sapien id nulla vehicula mollis.',
  'Nullam ornare quam nec nisl tincidunt, in molestie mauris scelerisque.',
  'Donec vestibulum nibh vel risus malesuada eleifend.',
].map((text, ix) => ({
  username: 'iam-kevin',
  text,
  timestamp: Date.now() - 1000 * ix,
}));
